### PR TITLE
fix the mark for the current active Python thread

### PR DESCRIPTION
**Pull request by albertz**
SIGALARM and SIGUSR1/2 will get delivered to any running thread. The current thread of the signal doesn't give any useful information. Try to get the current Python thread which holds the GIL, or use NULL.

Don't use `PyThreadState_Get()` because that will call `Py_FatalError()` in case it is not set. Instead access the variable `_PyThreadState_Current` directly. The variable datatype has been changed since Python 3.2, so we need the `#if` switch for Python >=3.2 or earlier.

You'll find similar code in CPython itself, e.g. [here](https://github.com/python/cpython/blob/4adc9d28a949c458f01517d89b32ed3995460aa8/Objects/dictobject.c) and [more](https://github.com/python/cpython/search?utf8=%E2%9C%93&q=_PyThreadState_Current).

### CODE REVIEW

**Comment by haypo** [comment]
> SIGALARM and SIGUSR1/2 will get delivered to any running thread.

Hum, I don't understand your change. You only modify the code when Python is compiled *without thread support*. Is your issue theoric or did you see it in practice? Can you show a code snippet to reproduce it?

> Don't use PyThreadState_Get() because that will call Py_FatalError() in case it is not set.

When does it occur when Python is compiled without thread support? faulthandler has tests trying to dump the traceback when the GIL is released.

**Comment by albertz** [comment]
I also changed `faulthandler_alarm` and `faulthandler_user`. The change in `faulthandler_fatal_error` was mostly for cosmetic reasons but I guess not necessary.

**Comment by albertz** [comment]
Code updated.

**Comment by haypo** [comment]
Can you please give some examples to test your change?

**Comment by albertz** [comment]
```
faulthandler.register(signal.SIGUSR1, all_threads=True)
```

Then send a `SIGUSR1` or `SIGALRM` to your process. Before my change, any random thread (*) was shown as "current thread". After my change, the current Python thread (if there is any) is shown as the "current thread".

(*) [Via](http://stackoverflow.com/a/2586964/133374):

From [signal(7)](http://linux.die.net/man/7/signal) man page:

> A process-directed signal may be delivered to any one of the threads that does not currently have the signal blocked. If more than one of the threads has the signal unblocked, then the kernel chooses an arbitrary thread to which to deliver the signal.

From [alarm(2)](http://linux.die.net/man/2/alarm) man page:

> alarm() arranges for a SIGALRM signal to be delivered to the process in seconds seconds.

So, the signal is delivered to a process (a signal might be directed at certain thread too) and thus we do not know which of the threads will receive it.

However, it may have been likely, depending on your Linux kernel (or Unix), that the thread which received the signal was the same as the current Python thread.

**Comment by haypo** [comment]
2015-04-08 14:34 GMT+02:00 Albert Zeyer <notifications@github.com>:

> faulthandler.register(signal.SIGUSR1, all_threads=True)
>
> Then send a SIGUSR1 or SIGALRM to your process.
>
Ok, but can you write a short program to show the problem? The best would
be to write an unit test.

**Comment by albertz** [comment]
```
os.kill(0, signal.SIGUSR1)
```
I'm not exactly sure what to test and how to test. Do you want a test which shows that in a signal handler, we can have
```
_PyThreadState_Current != NULL /* there is some active Python thread */ &&
_PyThreadState_Current != PyGILState_GetThisThreadState()
    /* the active Python thread differs from the current thread */
```
? That might be hard, because probably, in many cases, this is the case. Also, this depends on the Linux/Unix version/kernel and kernel configuration, and on the hardware.

It's also hard to tell that faulthandler has incorrectly shown the "current thread", because that can immediately change. To test that, you have somehow to ensure that you know the active Python thread and it wont change. To enforce this, you could write some C extension which basically does this:
```
PyObject* myfunc() { while(1); }
```
Then, you would create multiple threads. In all except one, you would just do this:
```
while True: pass
```
In one thread, you would call `myfunc`. `myfunc` will never release the GIL and thus be forever the current active Python thread. Then you could send many `SIGUSR1`s. Depending on your system, there might be a chance that you end up with the condition above (`_PyThreadState_Current != PyGILState_GetThisThreadState()`) -- however, not necessarily.

This would only be a test to show the bug in the old version. There is simply no way to ensure that this patch fixes it. You could just run this test a 1000 times on many different systems (different hardware, different Unixes) and only be sure to a certain degree.

**Comment by haypo** [comment]
Sorry, I failed to understand the issue and there is no activity since 2 years.

Anyway, this project is now a only backport for Python 2.7. I suggest you to report the issue upstream in CPython bug tracker: http://bugs.python.org/

**Pull request closed without merging**
