### PR TITLE
Show timestamp on scheduled thread-dumps 

### PR DESCRIPTION
**Pull request by stfp**
Hi!  Here's a quick stab at printing the current time (as a unix timestamp) on scheduled thread-dumps (it's cumbersome to correlate otherwise).

Output looks like:
-   1455771515 Timeout (0:01:00)!

Not much else to mention... We use a single, static buffer to avoid allocating memory at dump time. Most of the added code is copied from cpython.

Builds and runs on OSX and Linux, can't test windows.

### CODE REVIEW

**Comment by haypo** [comment]
Since you don't print subsecond resolution, why do you need time.c? I suggest to remove it and call directly time(), a resolution of 1 second is enough.

"1455771515 Timeout (0:01:00)!"

I don't like this format, it's hard to understand that 1455771515 is a timestamp. I would prefer something like:

"Timeout (0:01:00) at UTC epoch 1455771515!"

I suggest that the timezone is in UTC timestamp, no?

**Comment by haypo** [comment]
I would also prefer to have a single commit, since the overall change is simple enough.

**Comment by stfp** [comment]
Thanks for the quick review!  I'll add changes to this PR for now, and re-submit the final result as a single commit later.

Re: time(), I wasn't sure if windows or other platforms had time() or not. Since my ability to test and build is limited to recent OS X and Linux, I thought I would not even open the door to any possible compat issues and just grab code that's guaranteed to work where cpython does.

**Comment by haypo** [comment]
> Re: time(), I wasn't sure if windows or other platforms had time() or not.

All platform have time() :-)

**Comment by stfp** [comment]
Removing all that extra code works for me :)

Here's what I have now. I realized that snprintf isn't signal safe, so I switched to hand-rolled "itoa" loop.

**Comment by stfp** [comment]
Let me know if things look OK now and I'll re-submit a single-commit PR!

**Comment by stfp** [comment]
Re-submitted as https://github.com/haypo/faulthandler/pull/28

**Pull request closed without merging**
